/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package approject1.View;

import approject1.Controller.Admin;
import approject1.Controller.Beneficiary;
import approject1.Controller.Donor;
import approject1.Controller.Organization;
import approject1.Controller.Projects;
import approject1.Controller.Volunteer;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Farwa Malik
 */
public class MainUIOrg extends javax.swing.JFrame {

    /**
     * Creates new form MainUIOrg
     */
    Organization org;
    Projects proj;
    Admin admin;
    Donor don;
    Volunteer volun;
    Beneficiary ben;
    public MainUIOrg() {
        initComponents();
    }
    public MainUIOrg(Organization o) {
        org = o;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        organizationInfoPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        projectPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        organizationDonations = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        donorsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        donorsPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        donorsPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        organizationInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Name:");

        jLabel10.setText("User Name:");

        jLabel11.setText("Founding Date:");

        jButton4.setText("Update Organization Info");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setText("Department:");

        jLabel14.setText("Password:");

        jLabel23.setText(org.getName());

        jLabel24.setText(org.getUserName());

        jLabel25.setText(org.getFoundingDate().toString());

        jLabel26.setText(org.getDepartment());

        jLabel28.setText(org.getPassword());

        javax.swing.GroupLayout organizationInfoPanelLayout = new javax.swing.GroupLayout(organizationInfoPanel);
        organizationInfoPanel.setLayout(organizationInfoPanelLayout);
        organizationInfoPanelLayout.setHorizontalGroup(
            organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(organizationInfoPanelLayout.createSequentialGroup()
                .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(organizationInfoPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(161, 161, 161)
                        .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)))
                    .addGroup(organizationInfoPanelLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jButton4)))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        organizationInfoPanelLayout.setVerticalGroup(
            organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, organizationInfoPanelLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel23))
                .addGap(26, 26, 26)
                .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel24))
                .addGap(26, 26, 26)
                .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel25))
                .addGap(26, 26, 26)
                .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel26))
                .addGap(26, 26, 26)
                .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel14))
                .addGap(110, 110, 110)
                .addComponent(jButton4)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Organization Info", organizationInfoPanel);

        projectPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ArrayList<Projects> projects = new ArrayList<>();
        projects = org.loadProjects();
        Object[][] obj = new Object[projects.size()][3];
        int i =0;
        while(i < projects.size()){
            obj[i][0] = projects.get(i).getName();
            obj[i][1] = projects.get(i).getStartingDate();
            obj[i][2] = projects.get(i).getAdminName();

            i++;
        }
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            obj,
            new String [] {
                "Name", "Starting Date", "Admin Name"
            }
        ));
        jTable2.setCellSelectionEnabled(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable2MouseEntered(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable2KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("View Project");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add New Project");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout projectPanelLayout = new javax.swing.GroupLayout(projectPanel);
        projectPanel.setLayout(projectPanelLayout);
        projectPanelLayout.setHorizontalGroup(
            projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
            .addGroup(projectPanelLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addContainerGap(367, Short.MAX_VALUE))
        );
        projectPanelLayout.setVerticalGroup(
            projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectPanelLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Projects", projectPanel);

        organizationDonations.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ArrayList<Beneficiary> ben = new ArrayList<>();
        ben = org.loadBeneficiaries();
        Object[][] objBeneficiaryO = new Object[ben.size()][7];
        int iDO1 =0;
        while(iDO1< ben.size()){
            objBeneficiaryO[iDO1][0] = ben.get(iDO1).getBeneficiariesId();
            objBeneficiaryO[iDO1][1] = ben.get(iDO1).getName();
            objBeneficiaryO[iDO1][2] = ben.get(iDO1).getDateOfBirth();
            //System.out.println(donationsToOrg.get(iDO).getProjectName());
            objBeneficiaryO[iDO1][3] = ben.get(iDO1).getCity();
            objBeneficiaryO[iDO1][4] = ben.get(iDO1).getCountry();
            objBeneficiaryO[iDO1][5] = ben.get(iDO1).getPhoneNo();
            objBeneficiaryO[iDO1][6] = ben.get(iDO1).getEmail();

            iDO1++;
        }
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            objBeneficiaryO,
            new String [] {
                "Beneficiary ID"," Name ", "Date Of Birth",  "City","Country","Phone No","Email"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jButton9.setText("Add Beneficiary");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Delete Beneficiary");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout organizationDonationsLayout = new javax.swing.GroupLayout(organizationDonations);
        organizationDonations.setLayout(organizationDonationsLayout);
        organizationDonationsLayout.setHorizontalGroup(
            organizationDonationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, organizationDonationsLayout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addGap(275, 275, 275))
        );
        organizationDonationsLayout.setVerticalGroup(
            organizationDonationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, organizationDonationsLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(organizationDonationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Beneficiary", organizationDonations);

        donorsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ArrayList<Donor> donors = new ArrayList<>();
        donors = org.loadDonor();
        Object[][] objD = new Object[donors.size()][7];
        int iD =0;
        while(iD < donors.size()){
            objD[iD][0] = donors.get(iD).getDonorId();
            objD[iD][1] = donors.get(iD).getName();
            objD[iD][2] = donors.get(iD).getDateOfBirth();
            objD[iD][3] = donors.get(iD).getCity();
            objD[iD][4] = donors.get(iD).getCountry();
            objD[iD][5] = donors.get(iD).getPhoneNo();
            objD[iD][6] = donors.get(iD).getEmail();

            iD++;
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            objD,
            new String [] {
                "Name","DonorID" ,"Date of Birth", "City","Country","Phone No." ,"Email"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton6.setText("Add Donor");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Update Donor");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Delete Donor");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout donorsPanelLayout = new javax.swing.GroupLayout(donorsPanel);
        donorsPanel.setLayout(donorsPanelLayout);
        donorsPanelLayout.setHorizontalGroup(
            donorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
            .addGroup(donorsPanelLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        donorsPanelLayout.setVerticalGroup(
            donorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donorsPanelLayout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(donorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton8)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Donors", donorsPanel);

        donorsPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ArrayList<Admin> ad = new ArrayList<>();
        ad = org.loadAdmin();
        Object[][] objD1 = new Object[ad.size()][8];
        int iD1 =0;
        while(iD1 < ad.size()){
            objD1[iD1][0] = ad.get(iD1).getUserName();
            objD1[iD1][1] = ad.get(iD1).getName();
            objD1[iD1][2] = ad.get(iD1).getDateOfBirth();
            objD1[iD1][3] = ad.get(iD1).getJoiningDate();
            objD1[iD1][4] = ad.get(iD1).getCity();
            objD1[iD1][5] = ad.get(iD1).getpassword();
            objD1[iD1][6] = ad.get(iD1).getPhoneNo();
            objD1[iD1][7] = ad.get(iD1).getEmail();

            iD1++;
        }
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            objD1,
            new String [] {
                "User Name","Name" ,"Date of Birth", "Joining Date", "City","Password","Phone No." ,"Email"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton11.setText("Add Admin");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton13.setText("Delete Admin");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout donorsPanel1Layout = new javax.swing.GroupLayout(donorsPanel1);
        donorsPanel1.setLayout(donorsPanel1Layout);
        donorsPanel1Layout.setHorizontalGroup(
            donorsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
            .addGroup(donorsPanel1Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jButton11)
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        donorsPanel1Layout.setVerticalGroup(
            donorsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donorsPanel1Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(donorsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton13))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(donorsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(donorsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Admins", jPanel1);

        donorsPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ArrayList<Volunteer> v = new ArrayList<>();
        v = org.loadVolunteers();
        Object[][] objD3 = new Object[v.size()][7];
        int iD2 =0;
        while(iD2 < v.size()){
            objD3[iD2][0] = v.get(iD2).getVolunteerId();
            objD3[iD2][1] = v.get(iD2).getName();
            objD3[iD2][2] = v.get(iD2).getDateOfBirth();
            objD3[iD2][3] = v.get(iD2).getCity();
            objD3[iD2][4] = v.get(iD2).getCountry();
            objD3[iD2][5] = v.get(iD2).getPhoneNo();
            objD3[iD2][6] = v.get(iD2).getEmail();

            iD2++;
        }
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            objD3,
            new String [] {
                "Volunteer Serial Code","Name" ,"Date of Birth", "City","Country","Phone No." ,"Email"
            }
        ));
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jButton14.setText("Add Volunteer");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton16.setText("Delete Volunteer");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout donorsPanel2Layout = new javax.swing.GroupLayout(donorsPanel2);
        donorsPanel2.setLayout(donorsPanel2Layout);
        donorsPanel2Layout.setHorizontalGroup(
            donorsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
            .addGroup(donorsPanel2Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jButton14)
                .addGap(18, 18, 18)
                .addComponent(jButton16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        donorsPanel2Layout.setVerticalGroup(
            donorsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donorsPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(donorsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton16))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane4.addTab("", donorsPanel2);

        jTabbedPane1.addTab("Volunteer", jTabbedPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new UpdateOrganizationUI(org).setVisible(true);
        this.setVisible(false);
        //new MainUIOrg(org).setVisible(true);
        //this.dispose();
        //new MainUIOrg(org);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        String name = jTable2.getValueAt(jTable2.getSelectedRow(),0).toString();
        String dateOfBirth =  jTable2.getValueAt(jTable2.getSelectedRow(),1).toString();
        java.sql.Date date = java.sql.Date.valueOf(dateOfBirth);
        String adminName = jTable2.getValueAt(jTable2.getSelectedRow(),2).toString();
        proj = new Projects(adminName,name,date);
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseEntered

    private void jTable2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyTyped
        // TODO add your handling code here:
        boolean isEditing = jTable2.isEditing();
        if(!isEditing){
            JOptionPane.showMessageDialog(this, "Editing data on table not allowed");
        }
    }//GEN-LAST:event_jTable2KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(proj!=null)
        new ProjectInfo(proj).setVisible(true);
        else{
            JOptionPane.showMessageDialog(this, "kidnly select a project");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new AddProject().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        int Id =  (int) jTable4.getValueAt(jTable4.getSelectedRow(),0);
        String name = jTable4.getValueAt(jTable4.getSelectedRow(),1).toString();
        String dateOfBirth =  jTable4.getValueAt(jTable4.getSelectedRow(),2).toString();
        java.sql.Date date = java.sql.Date.valueOf(dateOfBirth);
        String City = jTable4.getValueAt(jTable4.getSelectedRow(),3).toString();
        String Country = jTable4.getValueAt(jTable4.getSelectedRow(),4).toString();
        String Phone = jTable4.getValueAt(jTable4.getSelectedRow(),5).toString();
        String email = jTable4.getValueAt(jTable4.getSelectedRow(),6).toString();
        ben = new Beneficiary(Id,name,date,City,Country,Phone,email);
    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        //Projects p =new Projects();
        new AddBeneficiary(org).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(ben!=null){
            System.out.println(ben.getBeneficiariesId());
            org.DeleteBeneficiary(ben.getBeneficiariesId());

            this.dispose();
            new MainUIOrg(org).setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "kindly select a beneficiary");

        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int Id =  (int) jTable1.getValueAt(jTable1.getSelectedRow(),0);
        String name = jTable1.getValueAt(jTable1.getSelectedRow(),1).toString();
        String dateOfBirth =  jTable1.getValueAt(jTable1.getSelectedRow(),2).toString();
        java.sql.Date date = java.sql.Date.valueOf(dateOfBirth);
        String City = jTable1.getValueAt(jTable1.getSelectedRow(),3).toString();
        String Country = jTable1.getValueAt(jTable1.getSelectedRow(),4).toString();
        String Phone = jTable1.getValueAt(jTable1.getSelectedRow(),5).toString();
        String email = jTable1.getValueAt(jTable1.getSelectedRow(),6).toString();
        don = new Donor(Id,name,date,City,Country,Phone,email);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        new AddDonor().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(don!=null){
            new UpdateDonor(don.getDonorId(),don).setVisible(true);
            this.dispose();
            new MainUI(org,admin).setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(don!=null){
            org.DeleteDonor(don.getDonorId());
            this.dispose();
            new MainUIOrg(org).setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "kindly select a donor");

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        String userName =  jTable3.getValueAt(jTable3.getSelectedRow(),0).toString();
        String name = jTable3.getValueAt(jTable3.getSelectedRow(),1).toString();
        String dateOfBirth =  jTable3.getValueAt(jTable3.getSelectedRow(),2).toString();
        java.sql.Date date = java.sql.Date.valueOf(dateOfBirth);
        String joiningDate =  jTable3.getValueAt(jTable3.getSelectedRow(),3).toString();
        java.sql.Date date1 = java.sql.Date.valueOf(joiningDate);
        String City = jTable3.getValueAt(jTable3.getSelectedRow(),4).toString();
        String password = jTable3.getValueAt(jTable3.getSelectedRow(),5).toString();
        String Phone = jTable3.getValueAt(jTable3.getSelectedRow(),6).toString();
        String email = jTable3.getValueAt(jTable3.getSelectedRow(),7).toString();
        admin = new Admin(userName,name,password,date,date1,City,Phone,email);

    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        new AddAdmin(org).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        if(admin!=null){
            org.DeleteAdmin(admin.getUserName());
            this.dispose();
            new MainUIOrg(org).setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "kindly select an admin");

        }

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        // TODO add your handling code here:
        int Id =  (int) jTable5.getValueAt(jTable5.getSelectedRow(),0);
        String name = jTable5.getValueAt(jTable5.getSelectedRow(),1).toString();
        String dateOfBirth =  jTable5.getValueAt(jTable5.getSelectedRow(),2).toString();
        java.sql.Date date = java.sql.Date.valueOf(dateOfBirth);
        String City = jTable5.getValueAt(jTable5.getSelectedRow(),3).toString();
        String Country = jTable5.getValueAt(jTable5.getSelectedRow(),4).toString();
        String Phone = jTable5.getValueAt(jTable5.getSelectedRow(),5).toString();
        String email = jTable5.getValueAt(jTable5.getSelectedRow(),6).toString();
        volun = new Volunteer(Id,name,date,City,Country,Phone,email);
    }//GEN-LAST:event_jTable5MouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        new AddVolunteer(org).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton16MouseClicked

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        if(volun!=null){
            org.DeleteVolunteer(volun.getVolunteerId());
            this.dispose();
            new MainUIOrg(org).setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "kindly select a volunteer");

        }

    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUIOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUIOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUIOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUIOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUIOrg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel donorsPanel;
    private javax.swing.JPanel donorsPanel1;
    private javax.swing.JPanel donorsPanel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JPanel organizationDonations;
    private javax.swing.JPanel organizationInfoPanel;
    private javax.swing.JPanel projectPanel;
    // End of variables declaration//GEN-END:variables
}
