/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package approject1.View;

import approject1.Controller.Admin;
import approject1.Controller.Donations;
import approject1.Controller.Donor;
import approject1.Controller.Organization;
import approject1.Controller.Projects;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Farwa Malik
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    
    
        Organization org;
        Admin admin;
        Projects proj;
        Donor don;
        Donations dona;
        int donorId;
        public MainUI() {
        initComponents();
    }
    public MainUI(Organization o,Admin a) {
        admin = a;
        org = o;
        System.out.println(a.getEmail());
        setVisible(true);
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        infoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        organizationInfoPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        projectPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        donorsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        organizationDonations = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        infoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Name:");

        jLabel2.setText("User Name:");

        jLabel3.setText("Date of Birth:");

        jLabel4.setText("City");

        jLabel5.setText("Joining Date:");

        jLabel6.setText("Phone no.");

        jLabel7.setText("Email:");

        jLabel8.setText("Password:");

        jButton3.setText("Update Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setText(admin.getPhoneNo());

        jLabel16.setText(admin.getName());

        jLabel17.setText(admin.getDateOfBirth().toString());

        jLabel18.setText(admin.getJoiningDate().toString());

        jLabel19.setText(admin.getpassword());

        jLabel20.setText(admin.getCity());

        jLabel21.setText(admin.getUserName());

        jLabel22.setText(admin.getEmail());

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(145, 145, 145)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)
                        .addGap(71, 71, 71)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel16))
                .addGap(28, 28, 28)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel21))
                .addGap(28, 28, 28)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel19))
                .addGap(28, 28, 28)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel20))
                .addGap(30, 30, 30)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel17))
                .addGap(31, 31, 31)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel18))
                .addGap(31, 31, 31)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15))
                .addGap(31, 31, 31)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel22))
                .addGap(44, 44, 44)
                .addComponent(jButton3)
                .addGap(71, 71, 71))
        );

        jTabbedPane1.addTab("My Info", infoPanel);

        organizationInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Name:");

        jLabel10.setText("User Name:");

        jLabel11.setText("Founding Date:");

        jLabel12.setText("Department:");

        jLabel14.setText("Password:");

        jLabel23.setText(org.getName());

        jLabel24.setText(org.getUserName());

        jLabel25.setText(org.getFoundingDate().toString());

        jLabel26.setText(org.getDepartment());

        jLabel28.setText(org.getPassword());

        javax.swing.GroupLayout organizationInfoPanelLayout = new javax.swing.GroupLayout(organizationInfoPanel);
        organizationInfoPanel.setLayout(organizationInfoPanelLayout);
        organizationInfoPanelLayout.setHorizontalGroup(
            organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(organizationInfoPanelLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(161, 161, 161)
                .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        organizationInfoPanelLayout.setVerticalGroup(
            organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, organizationInfoPanelLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel23))
                .addGap(26, 26, 26)
                .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel24))
                .addGap(26, 26, 26)
                .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel25))
                .addGap(26, 26, 26)
                .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel26))
                .addGap(26, 26, 26)
                .addGroup(organizationInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel14))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Organization Info", organizationInfoPanel);

        projectPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ArrayList<Projects> projects = new ArrayList<>();
        projects = org.loadProjects();
        Object[][] obj = new Object[projects.size()][3];
        int i =0;
        while(i < projects.size()){
            obj[i][0] = projects.get(i).getName();
            obj[i][1] = projects.get(i).getStartingDate();
            obj[i][2] = projects.get(i).getAdminName();

            i++;
        }
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            obj,
            new String [] {
                "Name", "Starting Date", "Admin Name"
            }
        ));
        jTable2.setCellSelectionEnabled(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTable2MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTable2KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("View Project");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add New Project");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Update Project");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton11.setText("Delete Project");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout projectPanelLayout = new javax.swing.GroupLayout(projectPanel);
        projectPanel.setLayout(projectPanelLayout);
        projectPanelLayout.setHorizontalGroup(
            projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(projectPanelLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jButton1)
                .addGap(36, 36, 36)
                .addComponent(jButton2)
                .addGap(39, 39, 39)
                .addComponent(jButton5)
                .addGap(37, 37, 37)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        projectPanelLayout.setVerticalGroup(
            projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, projectPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Projects", projectPanel);

        donorsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ArrayList<Donor> donors = new ArrayList<>();
        donors = org.loadDonor();
        Object[][] objD = new Object[donors.size()][7];
        int iD =0;
        while(iD < donors.size()){
            objD[iD][0] = donors.get(iD).getDonorId();
            objD[iD][1] = donors.get(iD).getName();
            objD[iD][2] = donors.get(iD).getDateOfBirth();
            objD[iD][3] = donors.get(iD).getCity();
            objD[iD][4] = donors.get(iD).getCountry();
            objD[iD][5] = donors.get(iD).getPhoneNo();
            objD[iD][6] = donors.get(iD).getEmail();

            iD++;
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            objD,
            new String [] {
                "Name","DonorID" ,"Date of Birth", "City","Country","Phone No." ,"Email"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton6.setText("Add Donor");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Update Donor");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout donorsPanelLayout = new javax.swing.GroupLayout(donorsPanel);
        donorsPanel.setLayout(donorsPanelLayout);
        donorsPanelLayout.setHorizontalGroup(
            donorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
            .addGroup(donorsPanelLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jButton6)
                .addGap(37, 37, 37)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        donorsPanelLayout.setVerticalGroup(
            donorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donorsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(donorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Donors", donorsPanel);

        organizationDonations.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ArrayList<Donations> donationsToOrg = new ArrayList<>();
        donationsToOrg = org.loadDonations();
        Object[][] objDonationsO = new Object[donationsToOrg.size()][6];
        int iDO =0;
        while(iDO< donationsToOrg.size()){
            objDonationsO[iDO][0] = donationsToOrg.get(iDO).getDonationId();
            objDonationsO[iDO][1] = donationsToOrg.get(iDO).getDonorId();
            objDonationsO[iDO][2] = donationsToOrg.get(iDO).getDonationType();
            System.out.println(donationsToOrg.get(iDO).getProjectName());
            objDonationsO[iDO][3] = donationsToOrg.get(iDO).getProjectName();
            objDonationsO[iDO][4] = donationsToOrg.get(iDO).getAmount();
            objDonationsO[iDO][5] = donationsToOrg.get(iDO).getDonationDate();

            iDO++;
        }
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            objDonationsO,
            new String [] {
                "Donation ID","Donor Serial Code", "Donation Type",  "Project Name","Amount","Donated On"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable4MouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jButton9.setText("Add Donation");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Delete Donation");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout organizationDonationsLayout = new javax.swing.GroupLayout(organizationDonations);
        organizationDonations.setLayout(organizationDonationsLayout);
        organizationDonationsLayout.setHorizontalGroup(
            organizationDonationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, organizationDonationsLayout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addGap(275, 275, 275))
        );
        organizationDonationsLayout.setVerticalGroup(
            organizationDonationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, organizationDonationsLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(organizationDonationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Donations to Organization ", organizationDonations);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new UpdateProfile(org,admin);
        this.setVisible(false);
        new MainUI(org,admin).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        String name =  jTable2.getValueAt(jTable2.getSelectedRow(),0).toString();
        String st_date =  jTable2.getValueAt(jTable2.getSelectedRow(),1).toString();
        java.sql.Date date = java.sql.Date.valueOf(st_date);
        String admin =  jTable2.getValueAt(jTable2.getSelectedRow(),2).toString();
        proj = new Projects(admin,name,date);

    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
        // TODO add your handling code here:
        jTable2.setRowHeight(jTable2.getSelectedRow(),5);
    }//GEN-LAST:event_jTable2MouseEntered

    private void jTable2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyTyped
        // TODO add your handling code here:
        boolean isEditing = jTable2.isEditing();
        if(!isEditing){
            JOptionPane.showMessageDialog(this, "Editing data on table not allowed");
        }
    }//GEN-LAST:event_jTable2KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(proj!=null)
        new ProjectInfo(proj).setVisible(true);
        else{
            JOptionPane.showMessageDialog(this, "kidnly select a project");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new AddProject().setVisible(true);
        this.setVisible(false);
        new MainUI(org,admin).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(proj!=null){
            if(proj.getAdminName().equals(admin.getUserName())){
                new UpdateProject(proj).setVisible(true);
                this.setVisible(false);
                new MainUI(org,admin).setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "only project admin can update a project");

            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(proj!=null){
            if(proj.getAdminName().equals(admin.getUserName())){
                org.DeleteProject(proj.getName());
                this.setVisible(false);
                new MainUI(org,admin).setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "only project admin can delete a project");

            }
        }
        else{
            JOptionPane.showMessageDialog(this, "kindly select a project");

        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        donorId =  (int) jTable1.getValueAt(jTable1.getSelectedRow(),0);
        String name = jTable1.getValueAt(jTable1.getSelectedRow(),1).toString();
        String dateOfBirth =  jTable1.getValueAt(jTable1.getSelectedRow(),2).toString();
        java.sql.Date date = java.sql.Date.valueOf(dateOfBirth);
        String City = jTable1.getValueAt(jTable1.getSelectedRow(),3).toString();
        String Country = jTable1.getValueAt(jTable1.getSelectedRow(),4).toString();
        String Phone = jTable1.getValueAt(jTable1.getSelectedRow(),5).toString();
        String email = jTable1.getValueAt(jTable1.getSelectedRow(),6).toString();
        don = new Donor(donorId,name,date,City,Country,Phone,email);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new AddDonor().setVisible(true);
        this.setVisible(false);
        new MainUI(org,admin).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        if(don!=null){
            new UpdateDonor(don.getDonorId(),don).setVisible(true);
            this.setVisible(false);
            new MainUI(org,admin).setVisible(true);
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new AddDonation(org,admin).setVisible(true);
        this.setVisible(false);
        new MainUI(org,admin).setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(dona!=null){
            org.DeleteDonation(dona.getDonationId());
                this.setVisible(false);
                new MainUI(org,admin).setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "kindly select a Donation");

        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        int Id =  (int) jTable4.getValueAt(jTable4.getSelectedRow(),0);
        int donorId =  (int) jTable4.getValueAt(jTable4.getSelectedRow(),1);
        String type = jTable4.getValueAt(jTable4.getSelectedRow(),2).toString();
        String projectName = jTable4.getValueAt(jTable4.getSelectedRow(),3).toString();
        int amount =  (int) jTable4.getValueAt(jTable4.getSelectedRow(),4);
        String donatedOn =  jTable4.getValueAt(jTable4.getSelectedRow(),5).toString();
        java.sql.Date date = java.sql.Date.valueOf(donatedOn);
        dona = new Donations(donorId,type,Id,amount,date,projectName);
    }//GEN-LAST:event_jTable4MouseClicked

    private void jTable4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseEntered
        // TODO add your handling code here:
        //jTable4.getSelectedRow().setRowHeight=500;
        
        jTable4.setRowHeight(jTable4.getSelectedRow(),5);
    }//GEN-LAST:event_jTable4MouseEntered

    private void jTable2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseExited
        // TODO add your handling code here:
        
        jTable2.setRowHeight(jTable2.getSelectedRow(),1);
    }//GEN-LAST:event_jTable2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel donorsPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JPanel organizationDonations;
    private javax.swing.JPanel organizationInfoPanel;
    private javax.swing.JPanel projectPanel;
    // End of variables declaration//GEN-END:variables
}
